name: flutter_vision
description: Plugin for managing Yolov5, Yolov8 and Yolov11 accessing with
  LiteRT (TensorFlow Lite) Support object detection and segmentation on
  Android. iOS, Working in progress.

version: 2.0.0

homepage: https://github.com/vladiH/flutter_vision

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  camera: ^0.11.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.vladih.computer_vision.flutter_vision
        pluginClass: FlutterVisionPlugin
      ios:
        pluginClass: FlutterVisionPlugin